thruster_manager:
  tf_prefix: mur
  base_link: base_link
  thruster_topic_prefix: thrusters/
  thruster_topic_suffix: /input
  thruster_frame_base: thruster_
  max_thrust: 5000
  timeout: -1
  update_rate: 50
  conversion_fcn: proportional
  conversion_fcn_params:
    gain: 0.0031
